# YAML pipeline


trigger:
 branches:
   include:
     - feature/*
     - main

pool: agents-ka-adda

variables:
  code-path: '$(System.DefaultWorkingDirectory)/'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(code-path)
    backendServiceArm: 'service-connection-2'
    backendAzureRmStorageAccountName: 'saneo25'
    backendAzureRmContainerName: 'statecontainer'
    backendAzureRmKey: 'yamlstate.tfstate'

- task: TerraformTask@5
  displayName: Terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(code-path)
    environmentServiceNameAzureRM: 'service-connection-2'
